name: docker-image
on:
  push:
    branches: [ "dev", "sam-custom" ]
  pull_request:
    branches: [ "dev" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # ref: docker-headless
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Call make
        run: |
          # VARS
          echo ${{ github.repository_owner }} #infrastlabs
          echo ${{ github.repository }}
          echo ${{ secrets.DOCKER_REGISTRY_PW_DOCKERHUB }} #fill not show in log
          
          # BUILD
          # echo core; cd ubt-core; sh buildx.sh #compile
          make clean;
          make;
      - name: Call buildx.sh(build with ali's cache, push)
        run: |
          # INFO
          pwd && ls -l
          docker version
          free -h; df -h; ip a |grep inet; uname -a;
          
          # ENV
          export DOCKER_REGISTRY_USER_infrastSubUser2=${{ secrets.DOCKER_REGISTRY_USER_INFRASTSUBUSER2 }}
          export DOCKER_REGISTRY_PW_infrastSubUser2=${{ secrets.DOCKER_REGISTRY_PW_INFRASTSUBUSER2 }}
          export DOCKER_REGISTRY_USER_dockerhub=${{ secrets.DOCKER_REGISTRY_USER_DOCKERHUB }}
          export DOCKER_REGISTRY_PW_dockerhub=${{ secrets.DOCKER_REGISTRY_PW_DOCKERHUB }}

          # BUILD
          # 
          BUILD_CONTAINER=barge-built
          mkdir -p brdata
          docker cp $BUILD_CONTAINER:/build/buildroot/dl brdata/build_buildroot_dl
          docker cp $BUILD_CONTAINER:/build/buildroot/ccache brdata/build_buildroot_ccache
          rm -rf brdata/build_buildroot_ccache/* #clear cache
          tar -zcf output/brdata.tar.gz brdata
          sh imgbuild.sh
